# This is the Alacritty configuration file. It is written in TOML format.
# ~/.config/alacritty/alacritty.toml
# 性能优化

[window]
startup_mode = "Maximized"
title = "Jin's Terminal"
dynamic_title = true 
decorations = "Buttonless"
opacity = 0.95
blur = true 
decorations_theme_variant="Dark"

[scrolling]
multiplier = 3
history = 10000

[env]
TERM = "xterm-256color"


[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 13 
builtin_box_drawing = true 

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[terminal]
shell={ program = "/bin/zsh", args = ["-l"] }


[keyboard]
bindings = [
    { key = "v", mods = "Command", action = "Paste" },
    { key = "c", mods = "Command", action = "Copy" },
    { key = "+", mods = "Command", action = "IncreaseFontSize" },
    { key = "-", mods = "Command", action = "DecreaseFontSize" },
    { key = "0", mods = "Command", action = "ResetFontSize" },
    { key = "M", mods = "Command", action = "ToggleMaximized" },
    { key = "h", mods = "Command", action = "Hide" },
    { key = "q", mods = "Command", action = "Quit" },
    { key = "n", mods = "Command|Shift", action = "SpawnNewInstance" },
    { key = "f", mods = "Command|Shift", action = "ToggleFullscreen" },
]
