unbind r
bind r source-file ~/.tmux.conf 

set -g prefix C-s
# act like vim
set -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

#resize panes with arrow mode-keys
bind-key -r S-Up resize-pane -U 
bind-key -r S-Down resize-pane -D
bind-key -r S-Left resize-pane -L
bind-key -r S-Right resize-pane -R

#hide and show pane
bind-key ! break-pane -d -n _hidden_pane
bind-key H join-pane -hs $.0
bind-key V join-pane -vs $.0

#split with current pane path
bind-key % split-window -c "#{pane_current_path}" -h
bind-key '"' split-window -c '#{pane_current_path}' 

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
# set -g @plugin 'catppuccin/tmux'

# set -g @catppuccin_flavor 'mocha'
set -g @dracula-show-powerline true
set -g @dracula-fixed-location "Shanghai"
set -g @dracula-show-fahrenheit false
set -g @dracula-show-weather true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon true
set -g status-position top

# initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
