// Call Unified Metering API

// @name=sendUsages-nc
POST http://localhost:4004/unified-metering/sendUsages
Content-Type: application/json
dwc-subaccount-id: c645be38-509d-4335-b0a3-bf772f0bbdf3
dwc-tenent: c645be38-509d-4335-b0a3-bf772f0bbdf2
Authorization: Basic BEM_ALL:Welcome1

{
    "usages" : [
       {
            "id": "c2214e4e-9629-42a0-8fbb-5d204c29c21b",
            "timestamp": "2025-05-21T01:30:00.339Z",
            "measure": {
                "id": "footprint-calculated",
                "value": 100
            }
        }
    ]
}

###
//@name=ingestUsages
// @certificate={{cert}}
// @certificate-key={{key}}
< {%
    const credentials = $xsenv.serviceCredentials({ name : "sfm-unified-metering" });
    request.variables.set("cert", credentials.certificate);
    request.variables.set("key", credentials.key);
    request.variables.set("endpoint", credentials.endpoints.usageIngestion);
    request.variables.set("meteringAccountName", credentials.meteringAccount.name);
%}
POST {{endpoint}}/v2/accounts/{{meteringAccountName}}/namespaces/metering/datastreams/btp$1/eventBatch
Content-Type: application/json

[
   {
        "id": "c2214e4e-9629-42a0-8fbb-5d204c29c21d",
        "timestamp": "2025-05-21T01:30:00.339Z",
        "consumer": {
            "region": "cf-eu20",
            "btp": {
                "environment": "CF",
                "subAccount": "c645be38-509d-4335-b0a3-bf772f0bbdf2"
            }
        },
        "product": {
            "service": {
                "id": "sustainability-footprint-management",
                "plan": "standard"
            }
        },
        "measure": {
            "id": "footprint-calculated",
            "value": 100
        }
    }
]

###
//@name=ingestUsages_curl
// @certificate cert.pem
// @certificate-key key.pem
POST https://input.eu.edp.services.cloud.sap/v2/accounts/metering_live_1ad0df7d_ef30_4f49_a557_0743d886dd4e/namespaces/metering/datastreams/btp$1/eventBatch
Content-Type: application/json

[
   {
        "id": "c2214e4e-9629-42a0-8fbb-5d204c29c21d",
        "timestamp": "2025-05-21T01:30:00.339Z",
        "consumer": {
            "region": "cf-eu20",
            "btp": {
                "environment": "CF",
                "subAccount": "c645be38-509d-4335-b0a3-bf772f0bbdf2"
            }
        },
        "product": {
            "service": {
                "id": "sustainability-footprint-management",
                "plan": "standard"
            }
        },
        "measure": {
            "id": "footprint-calculated",
            "value": 100
        }
    }
]

###
//@name=retreiveUsages
// @certificate={{cert}}
// @certificate-key={{key}}
< {%
    const credentials = $xsenv.serviceCredentials({ name : "sfm-unified-metering" });
    request.variables.set("cert", credentials.certificate);
    request.variables.set("key", credentials.key);
    request.variables.set("endpoint", credentials.endpoints.syncRetrieval);
    request.variables.set("meteringAccountName", credentials.meteringAccount.name);
%}
GET {{endpoint}}/v2/accounts/{{meteringAccountName}}/namespaces/metering/datastreams/btp$1/events
Content-Type: application/json

###
//@name=nc-metering-service
// @certificate={{CF_INSTANCE_CERT}}
// @certificate-key={{CF_INSTANCE_KEY}}
POST https://c21-eu20-c214bc14f17-019736ef-c82d-aa6a-69b5-43e96dcdce18.cfapps.eu20.hana.ondemand.com/unified-metering/sendUsages
Content-Type: application/json
dwc-subaccount-id: 03d9acb6-3078-48bb-935c-fd5f125c547b
dwc-tenent: 03d9acb6-3078-48bb-935c-fd5f125c547b

{
    "usages" : [
       {
            "id": "c2214e4e-9629-42a0-8fbb-5d204c29c21b",
            "timestamp": "2025-05-21T01:30:00.339Z",
            "measure": {
                "id": "footprint-calculated",
                "value": 100
            }
        }
    ]
}
